#!/usr/bin/env node
/* Generate make-kit/tokens.css from tokens/*.json.
 *
 *   node make-kit/build-tokens.js
 *
 * tokens/*.json is the single source of truth. Never hand-edit tokens.css —
 * edit the JSON and re-run this script.
 */
const fs = require("fs");
const path = require("path");

const TOKENS_DIR = path.join(__dirname, "..", "tokens");
const OUT = path.join(__dirname, "tokens.css");

const read = (name) =>
  JSON.parse(fs.readFileSync(path.join(TOKENS_DIR, name), "utf8"));

// camelCase / digit boundaries -> kebab: backgroundAlternate -> background-alternate,
// foreground20 -> foreground-20, onSurfaceBrand -> on-surface-brand.
const kebab = (s) =>
  String(s)
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])(\d)/g, "$1-$2")
    .toLowerCase();

// "theme.system.shadowElevation" -> var(--theme-system-shadow-elevation)
const refVar = (p) => `var(--${p.split(".").map(kebab).join("-")})`;

const line = (name, value) => `  --${name}: ${value};`;

// ---- static token groups (live in :root) --------------------------------

function spacingVars() {
  const { spacing } = read("spacing.json");
  return Object.entries(spacing).map(([k, v]) => line(`spacing-${kebab(k)}`, `${v}px`));
}

function radiusVars() {
  const { radius } = read("radius.json");
  return Object.entries(radius).map(([k, v]) => line(`radius-${kebab(k)}`, `${v}px`));
}

function breakpointVars() {
  const { breakpoints } = read("breakpoints.json");
  return Object.entries(breakpoints).map(([k, v]) => line(`breakpoint-${kebab(k)}`, `${v}px`));
}

function typographyVars() {
  const t = read("typography.json");
  const fam = t.fontFamily;
  const out = [
    line("font-family-default", `"${fam.default}", sans-serif`),
    line("font-family-icon", `"${fam.icon}"`),
  ];
  for (const [name, s] of Object.entries(t)) {
    if (name === "fontFamily") continue;
    const familyVar =
      s.fontFamily === fam.icon ? "var(--font-family-icon)" : "var(--font-family-default)";
    const lh = s.lineHeight ? `${s.lineHeight}px` : "1";
    // Typography style names are simple slugs (h1, body, label) — keep them
    // as-is; the digit-splitting kebab is only for theme keys (foreground20).
    out.push(line(`typography-${name.toLowerCase()}`, `${s.fontWeight} ${s.fontSize}px/${lh} ${familyVar}`));
  }
  return out;
}

function effectVars() {
  const e = read("effects.json");
  const shadow = (s) =>
    `${s.offsetX}px ${s.offsetY}px ${s.blur}px ${s.spread}px ${refVar(s.color)}`;
  const out = [];
  for (const [name, s] of Object.entries(e.shadow)) {
    out.push(line(`shadow-${kebab(name)}`, shadow(s)));
  }
  const o = e.focus.outline;
  out.push(line("focus-outline-width", `${o.outlineWidth}px`));
  out.push(line("focus-outline-offset", `${o.radiusOffset}px`));
  out.push(line("focus-outline-color", refVar(o.outlineColor)));
  out.push(line("focus-glow", shadow(e.focus.glow)));
  return out;
}

// ---- theme groups (per selector / mode) ---------------------------------

function themeVars(themeBlock) {
  const out = [];
  for (const [group, entries] of Object.entries(themeBlock)) {
    for (const [key, value] of Object.entries(entries)) {
      out.push(line(`theme-${kebab(group)}-${kebab(key)}`, value));
    }
  }
  return out;
}

// ---- assemble -----------------------------------------------------------

function build() {
  const { themes } = read("theme.json");

  const targets = [
    { selector: ":root", theme: "catapa", mode: "light", label: "catapa / light", statics: true },
    { selector: '.dark,\n[data-mode="dark"]', theme: "catapa", mode: "dark", label: "catapa / dark" },
    { selector: '[data-theme="harmony"]', theme: "harmony", mode: "light", label: "harmony / light" },
  ];

  const blocks = targets.map((t) => {
    const themeBlock = themes[t.theme] && themes[t.theme][t.mode];
    if (!themeBlock) return "";
    let body = "";
    if (t.statics) {
      body +=
        `  /* spacing */\n${spacingVars().join("\n")}\n\n` +
        `  /* radius */\n${radiusVars().join("\n")}\n\n` +
        `  /* typography */\n${typographyVars().join("\n")}\n\n` +
        `  /* effects */\n${effectVars().join("\n")}\n\n` +
        `  /* breakpoints */\n${breakpointVars().join("\n")}\n\n`;
    }
    body += `  /* theme: ${t.label} */\n${themeVars(themeBlock).join("\n")}`;
    return `${t.selector} {\n${body}\n}`;
  });

  const header =
    "/* Catalyst Design System — token layer for Figma Make.\n" +
    " * GENERATED by make-kit/build-tokens.js from tokens/*.json — DO NOT EDIT.\n" +
    " * Edit the JSON source and re-run: node make-kit/build-tokens.js\n" +
    " *\n" +
    " * Theme switching:\n" +
    " *   default                     -> catapa / light\n" +
    " *   .dark or [data-mode=\"dark\"]  -> catapa / dark\n" +
    " *   [data-theme=\"harmony\"]       -> harmony / light\n" +
    " */\n\n";

  fs.writeFileSync(OUT, header + blocks.filter(Boolean).join("\n\n") + "\n");
  console.log("Wrote " + path.relative(process.cwd(), OUT));
}

build();
